### ISSUE TITLE
PL= aka Payment threshold default value

### ISSUE THREAD

**Issue by Cryptominer937** [angelbbs/ZergPoolMinerLegacy#1]
pl= variable aka Payout threshold should default to 0 when adding wallets as 0 uses the pool minimum payout amount.

**Comment by angelbbs** [comment]
already used the minimal payload threshold
https://zergpool.com/payouts
“pl=0” reset threshold to minimal

**Comment by Cryptominer937** [comment]
![image](https://github.com/user-attachments/assets/ad506f89-8d67-499f-a88f-14d3ce46ef46)
this is the default value set by fork fix, this is far above the pool minimum payout.

**Comment by angelbbs** [comment]
will be fixed in next release

**Comment by Cryptominer937** [comment]
Looks good, Will report any other bugs I find. Great work by the way.
